name: Massai Mara Park 01 Dockerhub

on:
    workflow_dispatch

jobs:
    mmpark01_dockerhub:
        runs-on: ubuntu-22.04
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Login to docker hub
              uses: docker/login-action@v3
              with: 
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Docker operations
              run: |
                docker build -t ${{ secrets.DOCKER_USERNAME }}/massai_mara:v1 .
                docker push ${{ secrets.DOCKER_USERNAME }}/massai_mara:v1

            - name: Logout from docker hub
              if: always()
              run: docker logout

            - name: Run docker container
              run: |
                docker run -d --name mmpark01 -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/massai_mara:v1
                docker ps
                docker logs mmpark01

            - name: Run automated test #1
              run: |
                curl http://localhost:8080 || exit 1 
             
            - name: Run automated test #2
              run: |
                curl http://localhost:8080/images || exit 1                
              
            - name: Run automated test #3
              run: |
                curl http://localhost:8080/animal || exit 1 
               